add mise activation

diff --git a/dot_zshrc b/dot_zshrc
--- a/dot_zshrc
+++ b/dot_zshrc
@@ -81,3 +81,64 @@ eval "$(direnv hook zsh)"
 #THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
 export SDKMAN_DIR="$HOME/.sdkman"
 [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
+export PATH="/home/colin/.local/bin:$PATH"
+export MISE_SHELL=zsh
+export __MISE_ORIG_PATH="$PATH"
+export __MISE_ZSH_PRECMD_RUN=0
+
+mise() {
+  local command
+  command="${1:-}"
+  if [ "$#" = 0 ]; then
+    command /home/colin/.local/bin/mise
+    return
+  fi
+  shift
+
+  case "$command" in
+  deactivate|shell|sh)
+    # if argv doesn't contains -h,--help
+    if [[ ! " $@ " =~ " --help " ]] && [[ ! " $@ " =~ " -h " ]]; then
+      eval "$(command /home/colin/.local/bin/mise "$command" "$@")"
+      return $?
+    fi
+    ;;
+  esac
+  command /home/colin/.local/bin/mise "$command" "$@"
+}
+
+_mise_hook() {
+  eval "$(/home/colin/.local/bin/mise hook-env -s zsh)";
+}
+_mise_hook_precmd() {
+  eval "$(/home/colin/.local/bin/mise hook-env -s zsh --reason precmd)";
+}
+_mise_hook_chpwd() {
+  eval "$(/home/colin/.local/bin/mise hook-env -s zsh --reason chpwd)";
+}
+typeset -ag precmd_functions;
+if [[ -z "${precmd_functions[(r)_mise_hook_precmd]+1}" ]]; then
+  precmd_functions=( _mise_hook_precmd ${precmd_functions[@]} )
+fi
+typeset -ag chpwd_functions;
+if [[ -z "${chpwd_functions[(r)_mise_hook_chpwd]+1}" ]]; then
+  chpwd_functions=( _mise_hook_chpwd ${chpwd_functions[@]} )
+fi
+
+_mise_hook
+if [ -z "${_mise_cmd_not_found:-}" ]; then
+    _mise_cmd_not_found=1
+    [ -n "$(declare -f command_not_found_handler)" ] && eval "${$(declare -f command_not_found_handler)/command_not_found_handler/_command_not_found_handler}"
+
+    function command_not_found_handler() {
+        if [[ "$1" != "mise" && "$1" != "mise-"* ]] && /home/colin/.local/bin/mise hook-not-found -s zsh -- "$1"; then
+          _mise_hook
+          "$@"
+        elif [ -n "$(declare -f _command_not_found_handler)" ]; then
+            _command_not_found_handler "$@"
+        else
+            echo "zsh: command not found: $1" >&2
+            return 127
+        fi
+    }
+fi
